### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by u01jmg3**
👍🏻

### CODE REVIEW

**Comment by neklein** [comment]
@sheerun Could you merge so that we can use an updated version of rollup? The current version of rollup that you require is starting to cause dependency conflicts because it is out of date.

Thanks!

**Comment by sheerun** [comment]
@neklein Only if you promise to fix issues in case I merge. Unfortunately I don't have time to test exhaustively :)

**Comment by neklein** [comment]
@sheerun I've been testing in code and it seems fine there - I'll continue to verify.

I can't promise to fix for everyone. I understand if you would prefer not to merge at this time - I can just use the commit hash for now.

**Comment by sheerun** [comment]
I'll try to release soon

**Comment by u01jmg3** [comment]
I've updated the dependencies again - this will be my last attempt at getting this PR merged.

Provided the current version is tagged and then a new version is tagged, users can choose what to use if in the event issues occur by merging this PR.

**Comment by sheerun** [comment]
Released as 4.0.0

**Comment by sheerun** [comment]
Thank you @u01jmg3

**Pull request merged**
